QUESTIONS = [
    {"id": 1, "text": "I have a thing for large age differences in sexual encounters or relationships."},
    {"id": 2, "text": "I enjoy playing a different age than what I technically am."},
    {"id": 3, "text": "I enjoy dressing or behaving like a child, or engaging in child-appropriate activities such as coloring in a coloring book or going to a playground."},
    {"id": 4, "text": "I find it adorable when my partner acts or dresses childlike, or when they engage in childlike activities such as coloring in a coloring book or playing on a playground."},
    {"id": 5, "text": "I'll often put up a fight in bed, but that doesn't mean I want to win that fight at all."},
    {"id": 6, "text": "Talking back to one's dominant in a teasingly disobeying way, should be part of the sub's fun."},
    {"id": 7, "text": "I like being forced into submission, much more than submitting spontaneously."},
    {"id": 8, "text": "I don't mind a little playful resistance from my partner(s), in the end I'll win anyway."},
    {"id": 9, "text": "I like forcing my partner into submission, much more than them submitting spontaneously."},
    {"id": 10, "text": "Giving care, spoiling my partner, etc. is one of the main things I'm looking for in a relationship."},
    {"id": 11, "text": "I will naturally take on a nurturing and guiding, almost parental role in a relationship."},
    {"id": 12, "text": "I love making my partners do really disgusting things, purely for my own pleasure."},
    {"id": 13, "text": "Treating my partner with little or no respect during sex/BDSM arouses me."},
    {"id": 14, "text": "I like to sexually degrade and/or humiliate my partner(s) sometimes."},
    {"id": 15, "text": "I enjoy verbally degrading my partner or calling them humiliating names during sex/BDSM."},
    {"id": 16, "text": "I prefer making the sexual decisions for my partner, as this gives me more control."},
    {"id": 17, "text": "Ideally I could command my partner, and they'd obey like a puppet no matter what I tell them to do."},
    {"id": 18, "text": "I like to dominate my partner(s), especially in the bedroom."},
    {"id": 19, "text": "I want my partner to serve me and address me as a superior."},
    {"id": 20, "text": "I would like it when my partner is completely tied up during sex/BDSM."},
    {"id": 21, "text": "Being treated with little or no respect during sex/BDSM arouses me."},
    {"id": 22, "text": "I like to be sexually degraded and humiliated by my partner(s) sometimes."},
    {"id": 23, "text": "I enjoy being verbally degraded or being called humiliating names during sex/BDSM."},
    {"id": 24, "text": "Receiving care, being spoiled, etc. are some of the main things I'm looking for in a relationship."},
    {"id": 25, "text": "I like it when my partner takes on a nurturing and guiding, almost parental role in the relationship."},
    {"id": 26, "text": "I like receiving pain during sex/BDSM and seeing the results of it (marks/bruises, makeup running by tears, etc.) afterwards."},
    {"id": 27, "text": "I like to be totally helpless and at my partner's disposal, physically unable to resist what they do."},
    {"id": 28, "text": "Being in fear of what my partner is going to do to me physically, is arousing."},
    {"id": 29, "text": "The idea of being tortured sexually, is appealing."},
    {"id": 30, "text": "Having to do really disgusting things for my partner's pleasure sounds pretty arousing."},
    {"id": 31, "text": "When it comes to sexual acts, my own discomfort is pretty much irrelevant if it allows me to give my partner more pleasure."},
    {"id": 32, "text": "If my partner would really enjoy using me as a urinal, I would happily let them."},
    {"id": 33, "text": "I would like to provide my partner(s) with explicit slave training, i.e. train them in prescribed physical positions and rituals, etc."},
    {"id": 34, "text": "Living with a group of slaves owned by me and serving me, would be my ultimate life goal."},
    {"id": 35, "text": "I'd like my partner(s) to submit to me 24/7 and I'm willing to take the responsibility that comes with it."},
    {"id": 36, "text": "I would like to have sex with multiple people at the same time."},
    {"id": 37, "text": "I'm totally cool with my partner(s) having sex with other people."},
    {"id": 38, "text": "My partner having multiple partners, while I'm monogamous (except for threesomes with my partner involved) sounds like a perfectly acceptable situation."},
    {"id": 39, "text": "If I could not fulfil all of my partner's sexual desires, I would encourage them to see other people to fill the gaps."},
    {"id": 40, "text": "Assuming I was single, I would like to join an existing couple's or polygroup's relationship for sexual and/or emotional purposes."},
    {"id": 41, "text": "If part of my sexual desires are not fulfilled with my partner, I would want to see other people to fill the gaps."},
    {"id": 42, "text": "I enjoy keeping my partner as a pet: providing them with a cage, feeding them out of a bowl, petting/caressing them, etc."},
    {"id": 43, "text": "I enjoy it when my partner plays or acts like a pet animal (dog, cat, pony, etc.)"},
    {"id": 44, "text": "I enjoy feeling like a predator hunting its prey."},
    {"id": 45, "text": "I love seeing the fear in my partner's eyes when they know I'm going to inflict pain on them."},
    {"id": 46, "text": "Feeling physically overpowered is one of the most liberating sexual feelings."},
    {"id": 47, "text": "I enjoy playing or acting like a pet animal (dog, cat, pony, etc.)."},
    {"id": 48, "text": "I enjoy being kept as a pet: in a cage, eating out of a bowl, being petted/caressed, etc."},
    {"id": 49, "text": "I enjoy feeling like a prey hunted by a predator."},
    {"id": 50, "text": "I often behave in animalistic ways during sex (growling, howling, etc.)."},
    {"id": 51, "text": "Physically restricting my partner during sex/BDSM is arousing."},
    {"id": 52, "text": "I would like to be completely tied up during sex/BDSM."},
    {"id": 53, "text": "Being physically restricted during sex/BDSM (with clothes, attributes, rope, chains, etc.) is arousing."},
    {"id": 54, "text": "I like inflicting pain during sex/BDSM and seeing the results of it (marks/bruises, makeup running by tears, etc.) afterwards."},
    {"id": 55, "text": "When it comes to sexual acts, my partner's discomfort is pretty much irrelevant if it gives me more pleasure."},
    {"id": 56, "text": "Making my partner suffer for my pleasure is one of the best things in life."},
    {"id": 57, "text": "The idea of torturing someone sexually, is appealing."},
    {"id": 58, "text": "I currently have a Master/Mistress in my life."},
    {"id": 59, "text": "Being part of a group of slaves that serves one Master/Mistress, sounds like a life that would really suit me."},
    {"id": 60, "text": "In an ideal relationship, my partner would see me as a mere object: to them, I only exist when they're horny or when they need my service in some other way."},
    {"id": 61, "text": "I feel the need to serve my partner and treat them with the highest respect, addressing them as a superior."},
    {"id": 62, "text": "I would like to be nothing but a 24/7 sex slave."},
    {"id": 63, "text": "I like to be dominated, especially in the bedroom."},
    {"id": 64, "text": "I don't like making sexual decisions, I prefer my partner to make them for me."},
    {"id": 65, "text": "I like to be totally helpless and at my partner's disposal."},
    {"id": 66, "text": "My ultimate goal in life is to please my partner(s), and there's hardly anything I wouldn't do to reach that goal."},
    {"id": 67, "text": "In an ideal relationship, I should have no hard limits, my life should belong to my partner and they should decide what is good for me."},
    {"id": 68, "text": "I'll go a long way to make my appearance match my partner's desires."},
    {"id": 69, "text": "I like my partner(s) to be completely in charge in the bedroom, ordering me around."},
    {"id": 70, "text": "I don't need physical pleasure from sex: if my partner is enjoying it, that's all I need."},
    {"id": 71, "text": "I'd like to submit to my partner 24/7 and see serving them as my life purpose."},
    {"id": 72, "text": "I could be sexually submissive now, and dominant another time."},
    {"id": 73, "text": "I could not be always dominant or always submissive, I need both."},
    {"id": 74, "text": "I don't have any sort of specific fetish or non-standard sexual turn-on."},
    {"id": 75, "text": "I find the romantic aspect in a relationship much more important than the sexual or kinky aspects."},
    {"id": 76, "text": "I am currently in a long term relationship."},
    {"id": 77, "text": "I would be willing to leave everything I have behind, to live the BDSM-life of my dreams.."},
    {"id": 78, "text": "I have plenty of sexual fantasies that I would like to try out, more than most of my kinky peers."},
    {"id": 79, "text": "I enjoy watching other people being naked or having sex."},
    {"id": 80, "text": "I am willing to pay for porn if it really suits my sexual interests."},
    {"id": 81, "text": "Sometimes, watching people have sex is more fun than participating."},
    {"id": 82, "text": "I enjoy it when people watch me being naked or having sex."},
    {"id": 83, "text": "I like sending nude or sexual pictures/videos of myself to others."},
    {"id": 84, "text": "There is no reason why sex would have to happen in private spaces, isolated from the outside world."},
    {"id": 85, "text": "If I could make some money from selling porn clips of myself, I definitely would."},
    {"id": 86, "text": "I am willing to try anything once, even if I don't think I will like it."},
    {"id": 87, "text": "It's no big deal when things I try turn out bad for me. It's part of the risk and it's a necessary part of discovering what works and what doesn't."},
    {"id": 88, "text": "I have a need to constantly try new things."}
]

QUESTION_LOOKUP = {q["id"]: q for q in QUESTIONS}